### ISSUE TITLE
For each student, what year did they graduate Stanford CS PhD?

### ISSUE THREAD

**Issue by johnjosephhorton** [redmode/stanford_cs_phd#1]

**Comment by redmode** [comment]
I think we have it in
Q1: Get the list of Stanford CS PhD Graduates (GRADS)

**Comment by johnjosephhorton** [comment]
Excellent - so let's make a line chart showing the number of graduates per year - something like 

ggplot(data = df, aes(x = grad_year, y = num_grads)) + geom_line()

**Comment by johnjosephhorton** [comment]
@redmode I think it would be neat to add the plot as an svg or png & then display it in markdown on the README.md page. Let me know if this isn't clear and I'll do an example.

**Comment by redmode** [comment]
Done.
